config/routes.rb
Rails.application.routes.draw do
  resources :faculties
  devise_for :users
  root 'pages#landing'
  get 'pages/about'
  get '/profiles/:id' => 'profiles#show'
  resources :faculty do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :faculty
end

app/models/faculty.rb
class Faculty < ApplicationRecord
    has_many :comments
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :faculties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index,:show ]
  before_action :owner, only: [:edit, :update, :destroy]

  def index
    @faculties = Faculty.all
  end

 
  def show
  end

  
  def new
    @faculty = current_user.faculties.build #current_user.
  end

  
  def edit
  end

  
  def create
    @faculty = current_user.faculties.build(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    if(@faculty.update(faculty_params))
      redirect_to @faculty
    else
      render 'edit'
    end

  end

  
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def owner
      @faculty = current_user.faculties.find_by(id:params[:id])
      redirect_to faculties_path, notice: "У вас нет прав на изменение" if @faculty.nil?
    end
    def set_faculty
       @faculty = Faculty.find(params[:id])
    end

    def faculty_params
      params.require(:faculty).permit(:description)
    end
  end
def update
  respond_to do |format|
    if @faculty.update(faculty_params)
      format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
      format.json { render :show, status: :ok, location: @faculty }
    else
      format.html { render :edit }
      format.json { render json: @faculty.errors, status: :unprocessable_entity }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    redirect_to "/faculties"
  end
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :set_user    
    def show
    end
private
    def set_user
        @User = User.find(params[:id])
    end    
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description,class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<div class="card faculties-form ">
  <div class="card-header">
    <h2>Редактировать</h2>
  </div>
  <div class="card-body">


<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>
</div>
</div>

app/views/faculties/index.html.erb
<div class="jumbotron">
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.description %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><% if faculty.user == current_user %>
        <%= link_to 'Edit', edit_faculty_path(faculty) %>
        <% end %>
        </td>
        <td><% if faculty.user == current_user %>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in?%>
<%= link_to 'New Faculty', new_faculty_path,class:"btn btn-primary" %>
<% end %>
</div>

app/views/faculties/new.html.erb
<div class="card faculties-form ">
  <div class="card-header">
    <h2>Создать факультет</h2>
  </div>
  <div class="card-body">


<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>
</div>
</div>

app/views/faculties/show.html.erb
<div class="card faculties-form ">
  <div class="card-header">
    


<p>
  <strong>Description:</strong>
  <%= @faculty.description %>
</p>
<% if @faculty.user == current_user %>
<%= link_to 'Edit', edit_faculty_path(@faculty) %> 
<% end %>
<%= link_to 'Back', faculties_path %>
</div>
</div>
<p>
  <strong>Инофрмация о факультете:</strong>
  <%= @faculty.description %>
</p>

app/views/layouts/_navigation.html.erb
<%if user_signed_in? %>   
<nav class="navbar navbar-expand-lg navbar-light bg-ligh" style="background-color: #91b496;">
  <%= link_to "BNTU", root_path, class:'nav-brand text-logo landing-logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <DIV>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav">
    <div class="text-right">
      <li class="nav-item active ";>
       <%= link_to current_user.email, edit_user_registration_path, class:'nav-landing' %>
      </li>
      <li class="nav-item">
        <%= link_to "Выйти", destroy_user_session_path, method: :delete, class:'nav-landing' %>
    </div>
      </li>
    </ul>
  </div>
</nav>



<% else %>

<nav class="navbar navbar-expand-lg bg-transparent" style="background-color: #91b496;">
  <%= link_to "BNTU", root_path, class:'nav-brand text-logo landing-logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
    </span>
  </button>
  <DIV>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav">
    <div class="text-right">
        <%= link_to "О нас", pages_about_path, class:'nav-landing' %>
        <%= link_to "Войти", new_user_session_path, class:'nav-landing' %>
    </div>
    </ul>
  </div>
</nav>      
</ul>
<% end %>  
    
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kurs2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<% if user_signed_in? %>
    <div class="container-fluid  container-login bg-grey">
<% else %>
    <div class="container-fluid container-background container-login">
<% end %>

    <%= render "layouts/navigation" %>  
      <div class="container">
  <!-- Content here -->
           
        
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

    <%= yield %>
</div>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1 class="display-4">О нас:</h1>
  <p class="lead">Автор: Олег Неверовский.</p>


  </p>
</div>

app/views/pages/landing.html.erb
<% if user_signed_in? %>

<%else %>
<div class="jumbotron jumbotron-landing">
  <h1 class="display-4">Привет, студент!</h1>
  <p class="lead">Этот сайт тебе поможет (пока не придумал в чем).</p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to "Регистрация",new_user_registration_path, class:"btn btn-primary" %>
    <%= link_to "Войти", new_user_session_path, class:"btn btn-secondary" %>
  </p>
</div>

<%end%>

app/views/profiles/show.html.erb
<%# <%= @user.id %>
<%#<%= @user.email %>